# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkUEoHGLLeKVTNV3qe3INwBM7eCJVuLI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/Employee Dataset (1).csv')

data.head()

data.shape

data.info()

# Create a scatter plot of the "Age" and "Employee Salary" features

plt.figure(figsize = (10,5))

sns.scatterplot(data = data, x = 'age', y = 'salary', color = 'blue',
                edgecolor = 'linen', alpha = 0.7)

plt.title("Scatterplot of Employee Age v/s Employee Salary")
plt.xlabel('Employee Age')
plt.ylabel('Employee Salary')
plt.show()

# Create a scatter plot of the "Healthy_eating" and "Active_lifestyle" features

plt.figure(figsize = (10,5))

sns.scatterplot(data = data, x = 'healthy_eating', y = 'active_lifestyle', color = 'Red',
                edgecolor = 'linen', alpha = 0.7)

plt.title("Scatterplot of healthy_eating v/s active_lifestyle")
plt.xlabel('Helthy eat')
plt.ylabel('Active lifestyle')
plt.show()

# Create a scatter plot of the "Healthy_eating" and "Salary" features

plt.figure(figsize = (10,5))

sns.scatterplot(data = data, x = 'healthy_eating', y = 'salary', color = 'Green',
                edgecolor = 'linen', alpha = 0.7)

plt.title("Scatterplot of healthy_eating v/s active_lifestyle")
plt.xlabel('Helthy eat')
plt.ylabel('Salary')
plt.show()

# Create a count plot of the "groups" feature

plt.figure(figsize = (10,5))

sns.countplot(data = data ,x = 'groups', edgecolor = 'linen', alpha = 0.7)

plt.title("Count Plot of Groups")
plt.xlabel('Groups')
plt.ylabel('Count')
plt.show()

# Create a histogram of the "Salary" feature

plt.figure(figsize = (11,6))

sns.histplot(data = data ,x = 'salary', color = 'orange',
             edgecolor = 'linen', alpha = 0.7, bins = 10)

plt.title("Histogram of Salary")
plt.xlabel('Salary')
plt.ylabel('Count')
plt.show()

# Employee healthy eating grater than eight

sub1 = data[data['healthy_eating'] > 8]
print(sub1)

# Employee salary less than 1000

sub2 = data[data['salary'] < 1000]
print(sub2)

sub3 =  data[(data['healthy_eating'] > 8) & ( data['salary'] < 1000) ]
sub3